/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Represents a versioned client configuration record.
    /// </summary>
    [DataContract(Name = "ClientConfigurationResponse")]
    public partial class ClientConfigurationResponse : IEquatable<ClientConfigurationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientConfigurationResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClientConfigurationResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientConfigurationResponse" /> class.
        /// </summary>
        /// <param name="name">The logical name of the configuration. (required).</param>
        /// <param name="configType">The category of configuration. (required).</param>
        /// <param name="majorVersion">The major version number. (required).</param>
        /// <param name="minorVersion">The minor version number. (required).</param>
        /// <param name="value">The JSON configuration value. (required).</param>
        /// <param name="isDraft">Whether this version is still in draft state. Draft versions can be edited; locked versions cannot. (required).</param>
        public ClientConfigurationResponse(string name = default(string), string configType = default(string), int majorVersion = default(int), int minorVersion = default(int), string value = default(string), bool isDraft = default(bool))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ClientConfigurationResponse and cannot be null");
            }
            this.Name = name;
            // to ensure "configType" is required (not null)
            if (configType == null)
            {
                throw new ArgumentNullException("configType is a required property for ClientConfigurationResponse and cannot be null");
            }
            this.ConfigType = configType;
            this.MajorVersion = majorVersion;
            this.MinorVersion = minorVersion;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for ClientConfigurationResponse and cannot be null");
            }
            this.Value = value;
            this.IsDraft = isDraft;
        }

        /// <summary>
        /// The logical name of the configuration.
        /// </summary>
        /// <value>The logical name of the configuration.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The category of configuration.
        /// </summary>
        /// <value>The category of configuration.</value>
        [DataMember(Name = "configType", IsRequired = true, EmitDefaultValue = true)]
        public string ConfigType { get; set; }

        /// <summary>
        /// The major version number.
        /// </summary>
        /// <value>The major version number.</value>
        [DataMember(Name = "majorVersion", IsRequired = true, EmitDefaultValue = true)]
        public int MajorVersion { get; set; }

        /// <summary>
        /// The minor version number.
        /// </summary>
        /// <value>The minor version number.</value>
        [DataMember(Name = "minorVersion", IsRequired = true, EmitDefaultValue = true)]
        public int MinorVersion { get; set; }

        /// <summary>
        /// The JSON configuration value.
        /// </summary>
        /// <value>The JSON configuration value.</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Whether this version is still in draft state. Draft versions can be edited; locked versions cannot.
        /// </summary>
        /// <value>Whether this version is still in draft state. Draft versions can be edited; locked versions cannot.</value>
        [DataMember(Name = "isDraft", IsRequired = true, EmitDefaultValue = true)]
        public bool IsDraft { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClientConfigurationResponse {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ConfigType: ").Append(ConfigType).Append("\n");
            sb.Append("  MajorVersion: ").Append(MajorVersion).Append("\n");
            sb.Append("  MinorVersion: ").Append(MinorVersion).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  IsDraft: ").Append(IsDraft).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ClientConfigurationResponse);
        }

        /// <summary>
        /// Returns true if ClientConfigurationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ClientConfigurationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClientConfigurationResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ConfigType == input.ConfigType ||
                    (this.ConfigType != null &&
                    this.ConfigType.Equals(input.ConfigType))
                ) && 
                (
                    this.MajorVersion == input.MajorVersion ||
                    this.MajorVersion.Equals(input.MajorVersion)
                ) && 
                (
                    this.MinorVersion == input.MinorVersion ||
                    this.MinorVersion.Equals(input.MinorVersion)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.IsDraft == input.IsDraft ||
                    this.IsDraft.Equals(input.IsDraft)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.ConfigType != null)
                {
                    hashCode = (hashCode * 59) + this.ConfigType.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.MajorVersion.GetHashCode();
                hashCode = (hashCode * 59) + this.MinorVersion.GetHashCode();
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsDraft.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
