/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Request to create a new draft versioned configuration.
    /// </summary>
    [DataContract(Name = "CreateVersionedConfigurationDraftRequest")]
    public partial class CreateVersionedConfigurationDraftRequest : IEquatable<CreateVersionedConfigurationDraftRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateVersionedConfigurationDraftRequest" /> class.
        /// </summary>
        /// <param name="majorVersion">The major version for the new draft. Must be supplied together with minorVersion, or both omitted to auto-assign the next version..</param>
        /// <param name="minorVersion">The minor version for the new draft. Must be supplied together with MajorVersion, or both omitted to auto-assign the next version..</param>
        /// <param name="sourceMajorVersion">The major version of an existing record to copy the value from. Must be supplied together with SourceMinorVersion. If omitted, the new draft is initialised with an empty JSON object..</param>
        /// <param name="sourceMinorVersion">The minor version of an existing record to copy the value from. Must be supplied together with SourceMajorVersion. If omitted, the new draft is initialised with an empty JSON object..</param>
        /// <param name="value">The initial JSON value for the new draft. If omitted, the draft is initialised with an empty JSON object. Cannot be supplied together with SourceMajorVersion/SourceMinorVersion..</param>
        public CreateVersionedConfigurationDraftRequest(int? majorVersion = default(int?), int? minorVersion = default(int?), int? sourceMajorVersion = default(int?), int? sourceMinorVersion = default(int?), string value = default(string))
        {
            this.MajorVersion = majorVersion;
            this.MinorVersion = minorVersion;
            this.SourceMajorVersion = sourceMajorVersion;
            this.SourceMinorVersion = sourceMinorVersion;
            this.Value = value;
        }

        /// <summary>
        /// The major version for the new draft. Must be supplied together with minorVersion, or both omitted to auto-assign the next version.
        /// </summary>
        /// <value>The major version for the new draft. Must be supplied together with minorVersion, or both omitted to auto-assign the next version.</value>
        [DataMember(Name = "majorVersion", EmitDefaultValue = true)]
        public int? MajorVersion { get; set; }

        /// <summary>
        /// The minor version for the new draft. Must be supplied together with MajorVersion, or both omitted to auto-assign the next version.
        /// </summary>
        /// <value>The minor version for the new draft. Must be supplied together with MajorVersion, or both omitted to auto-assign the next version.</value>
        [DataMember(Name = "minorVersion", EmitDefaultValue = true)]
        public int? MinorVersion { get; set; }

        /// <summary>
        /// The major version of an existing record to copy the value from. Must be supplied together with SourceMinorVersion. If omitted, the new draft is initialised with an empty JSON object.
        /// </summary>
        /// <value>The major version of an existing record to copy the value from. Must be supplied together with SourceMinorVersion. If omitted, the new draft is initialised with an empty JSON object.</value>
        [DataMember(Name = "sourceMajorVersion", EmitDefaultValue = true)]
        public int? SourceMajorVersion { get; set; }

        /// <summary>
        /// The minor version of an existing record to copy the value from. Must be supplied together with SourceMajorVersion. If omitted, the new draft is initialised with an empty JSON object.
        /// </summary>
        /// <value>The minor version of an existing record to copy the value from. Must be supplied together with SourceMajorVersion. If omitted, the new draft is initialised with an empty JSON object.</value>
        [DataMember(Name = "sourceMinorVersion", EmitDefaultValue = true)]
        public int? SourceMinorVersion { get; set; }

        /// <summary>
        /// The initial JSON value for the new draft. If omitted, the draft is initialised with an empty JSON object. Cannot be supplied together with SourceMajorVersion/SourceMinorVersion.
        /// </summary>
        /// <value>The initial JSON value for the new draft. If omitted, the draft is initialised with an empty JSON object. Cannot be supplied together with SourceMajorVersion/SourceMinorVersion.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateVersionedConfigurationDraftRequest {\n");
            sb.Append("  MajorVersion: ").Append(MajorVersion).Append("\n");
            sb.Append("  MinorVersion: ").Append(MinorVersion).Append("\n");
            sb.Append("  SourceMajorVersion: ").Append(SourceMajorVersion).Append("\n");
            sb.Append("  SourceMinorVersion: ").Append(SourceMinorVersion).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateVersionedConfigurationDraftRequest);
        }

        /// <summary>
        /// Returns true if CreateVersionedConfigurationDraftRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateVersionedConfigurationDraftRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateVersionedConfigurationDraftRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MajorVersion == input.MajorVersion ||
                    (this.MajorVersion != null &&
                    this.MajorVersion.Equals(input.MajorVersion))
                ) && 
                (
                    this.MinorVersion == input.MinorVersion ||
                    (this.MinorVersion != null &&
                    this.MinorVersion.Equals(input.MinorVersion))
                ) && 
                (
                    this.SourceMajorVersion == input.SourceMajorVersion ||
                    (this.SourceMajorVersion != null &&
                    this.SourceMajorVersion.Equals(input.SourceMajorVersion))
                ) && 
                (
                    this.SourceMinorVersion == input.SourceMinorVersion ||
                    (this.SourceMinorVersion != null &&
                    this.SourceMinorVersion.Equals(input.SourceMinorVersion))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MajorVersion != null)
                {
                    hashCode = (hashCode * 59) + this.MajorVersion.GetHashCode();
                }
                if (this.MinorVersion != null)
                {
                    hashCode = (hashCode * 59) + this.MinorVersion.GetHashCode();
                }
                if (this.SourceMajorVersion != null)
                {
                    hashCode = (hashCode * 59) + this.SourceMajorVersion.GetHashCode();
                }
                if (this.SourceMinorVersion != null)
                {
                    hashCode = (hashCode * 59) + this.SourceMinorVersion.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Value (string) maxLength
            if (this.Value != null && this.Value.Length > 100000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, length must be less than 100000.", new [] { "Value" });
            }

            // Value (string) minLength
            if (this.Value != null && this.Value.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, length must be greater than 0.", new [] { "Value" });
            }

            yield break;
        }
    }
}
