/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// record containing a list of instances.
    /// </summary>
    [DataContract(Name = "InstancesResponse")]
    public partial class InstancesResponse : IEquatable<InstancesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstancesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstancesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstancesResponse" /> class.
        /// </summary>
        /// <param name="instances">instances (required).</param>
        public InstancesResponse(List<InstanceResponse> instances = default(List<InstanceResponse>))
        {
            // to ensure "instances" is required (not null)
            if (instances == null)
            {
                throw new ArgumentNullException("instances is a required property for InstancesResponse and cannot be null");
            }
            this.Instances = instances;
        }

        /// <summary>
        /// Gets or Sets Instances
        /// </summary>
        [DataMember(Name = "instances", IsRequired = true, EmitDefaultValue = true)]
        public List<InstanceResponse> Instances { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstancesResponse {\n");
            sb.Append("  Instances: ").Append(Instances).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InstancesResponse);
        }

        /// <summary>
        /// Returns true if InstancesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of InstancesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InstancesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Instances == input.Instances ||
                    this.Instances != null &&
                    input.Instances != null &&
                    this.Instances.SequenceEqual(input.Instances)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Instances != null)
                {
                    hashCode = (hashCode * 59) + this.Instances.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
