/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// record containing the 24-hour run summary grouped by external status.
    /// </summary>
    [DataContract(Name = "LatestRunsResponse")]
    public partial class LatestRunsResponse : IEquatable<LatestRunsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LatestRunsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LatestRunsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LatestRunsResponse" /> class.
        /// </summary>
        /// <param name="total">total (required).</param>
        /// <param name="statusCounts">statusCounts (required).</param>
        public LatestRunsResponse(int total = default(int), List<RunStatusCount> statusCounts = default(List<RunStatusCount>))
        {
            this.Total = total;
            // to ensure "statusCounts" is required (not null)
            if (statusCounts == null)
            {
                throw new ArgumentNullException("statusCounts is a required property for LatestRunsResponse and cannot be null");
            }
            this.StatusCounts = statusCounts;
        }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets StatusCounts
        /// </summary>
        [DataMember(Name = "statusCounts", IsRequired = true, EmitDefaultValue = true)]
        public List<RunStatusCount> StatusCounts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LatestRunsResponse {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  StatusCounts: ").Append(StatusCounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LatestRunsResponse);
        }

        /// <summary>
        /// Returns true if LatestRunsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LatestRunsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LatestRunsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                ) && 
                (
                    this.StatusCounts == input.StatusCounts ||
                    this.StatusCounts != null &&
                    input.StatusCounts != null &&
                    this.StatusCounts.SequenceEqual(input.StatusCounts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Total.GetHashCode();
                if (this.StatusCounts != null)
                {
                    hashCode = (hashCode * 59) + this.StatusCounts.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
