/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// OpenFigi API Parameters that have a restricted / permitted range of values.
    /// </summary>
    /// <value>OpenFigi API Parameters that have a restricted / permitted range of values.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OpenFigiParameterOptionName
    {
        /// <summary>
        /// Enum IdType for value: IdType
        /// </summary>
        [EnumMember(Value = "IdType")]
        IdType = 1,

        /// <summary>
        /// Enum ExchangeCode for value: ExchangeCode
        /// </summary>
        [EnumMember(Value = "ExchangeCode")]
        ExchangeCode = 2,

        /// <summary>
        /// Enum MicCode for value: MicCode
        /// </summary>
        [EnumMember(Value = "MicCode")]
        MicCode = 3,

        /// <summary>
        /// Enum Currency for value: Currency
        /// </summary>
        [EnumMember(Value = "Currency")]
        Currency = 4,

        /// <summary>
        /// Enum MarketSector for value: MarketSector
        /// </summary>
        [EnumMember(Value = "MarketSector")]
        MarketSector = 5,

        /// <summary>
        /// Enum SecurityType for value: SecurityType
        /// </summary>
        [EnumMember(Value = "SecurityType")]
        SecurityType = 6,

        /// <summary>
        /// Enum GeneralSecurityType for value: GeneralSecurityType
        /// </summary>
        [EnumMember(Value = "GeneralSecurityType")]
        GeneralSecurityType = 7,

        /// <summary>
        /// Enum StateCode for value: StateCode
        /// </summary>
        [EnumMember(Value = "StateCode")]
        StateCode = 8
    }

}
