/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// record containing details of a single file for a run.
    /// </summary>
    [DataContract(Name = "RunFileResponse")]
    public partial class RunFileResponse : IEquatable<RunFileResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunFileResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RunFileResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RunFileResponse" /> class.
        /// </summary>
        /// <param name="fileName">fileName (required).</param>
        /// <param name="generatedAt">generatedAt (required).</param>
        /// <param name="rowCount">rowCount (required).</param>
        /// <param name="fileHash">fileHash (required).</param>
        /// <param name="encrypted">encrypted (required).</param>
        /// <param name="destinations">destinations (required).</param>
        /// <param name="transactionIds">transactionIds (required).</param>
        public RunFileResponse(string fileName = default(string), DateTimeOffset generatedAt = default(DateTimeOffset), int rowCount = default(int), string fileHash = default(string), bool encrypted = default(bool), List<FileDestinationResponse> destinations = default(List<FileDestinationResponse>), List<Guid> transactionIds = default(List<Guid>))
        {
            // to ensure "fileName" is required (not null)
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName is a required property for RunFileResponse and cannot be null");
            }
            this.FileName = fileName;
            this.GeneratedAt = generatedAt;
            this.RowCount = rowCount;
            // to ensure "fileHash" is required (not null)
            if (fileHash == null)
            {
                throw new ArgumentNullException("fileHash is a required property for RunFileResponse and cannot be null");
            }
            this.FileHash = fileHash;
            this.Encrypted = encrypted;
            // to ensure "destinations" is required (not null)
            if (destinations == null)
            {
                throw new ArgumentNullException("destinations is a required property for RunFileResponse and cannot be null");
            }
            this.Destinations = destinations;
            // to ensure "transactionIds" is required (not null)
            if (transactionIds == null)
            {
                throw new ArgumentNullException("transactionIds is a required property for RunFileResponse and cannot be null");
            }
            this.TransactionIds = transactionIds;
        }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [DataMember(Name = "fileName", IsRequired = true, EmitDefaultValue = true)]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets GeneratedAt
        /// </summary>
        [DataMember(Name = "generatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset GeneratedAt { get; set; }

        /// <summary>
        /// Gets or Sets RowCount
        /// </summary>
        [DataMember(Name = "rowCount", IsRequired = true, EmitDefaultValue = true)]
        public int RowCount { get; set; }

        /// <summary>
        /// Gets or Sets FileHash
        /// </summary>
        [DataMember(Name = "fileHash", IsRequired = true, EmitDefaultValue = true)]
        public string FileHash { get; set; }

        /// <summary>
        /// Gets or Sets Encrypted
        /// </summary>
        [DataMember(Name = "encrypted", IsRequired = true, EmitDefaultValue = true)]
        public bool Encrypted { get; set; }

        /// <summary>
        /// Gets or Sets Destinations
        /// </summary>
        [DataMember(Name = "destinations", IsRequired = true, EmitDefaultValue = true)]
        public List<FileDestinationResponse> Destinations { get; set; }

        /// <summary>
        /// Gets or Sets TransactionIds
        /// </summary>
        [DataMember(Name = "transactionIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> TransactionIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunFileResponse {\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  GeneratedAt: ").Append(GeneratedAt).Append("\n");
            sb.Append("  RowCount: ").Append(RowCount).Append("\n");
            sb.Append("  FileHash: ").Append(FileHash).Append("\n");
            sb.Append("  Encrypted: ").Append(Encrypted).Append("\n");
            sb.Append("  Destinations: ").Append(Destinations).Append("\n");
            sb.Append("  TransactionIds: ").Append(TransactionIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RunFileResponse);
        }

        /// <summary>
        /// Returns true if RunFileResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RunFileResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RunFileResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.GeneratedAt == input.GeneratedAt ||
                    (this.GeneratedAt != null &&
                    this.GeneratedAt.Equals(input.GeneratedAt))
                ) && 
                (
                    this.RowCount == input.RowCount ||
                    this.RowCount.Equals(input.RowCount)
                ) && 
                (
                    this.FileHash == input.FileHash ||
                    (this.FileHash != null &&
                    this.FileHash.Equals(input.FileHash))
                ) && 
                (
                    this.Encrypted == input.Encrypted ||
                    this.Encrypted.Equals(input.Encrypted)
                ) && 
                (
                    this.Destinations == input.Destinations ||
                    this.Destinations != null &&
                    input.Destinations != null &&
                    this.Destinations.SequenceEqual(input.Destinations)
                ) && 
                (
                    this.TransactionIds == input.TransactionIds ||
                    this.TransactionIds != null &&
                    input.TransactionIds != null &&
                    this.TransactionIds.SequenceEqual(input.TransactionIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FileName != null)
                {
                    hashCode = (hashCode * 59) + this.FileName.GetHashCode();
                }
                if (this.GeneratedAt != null)
                {
                    hashCode = (hashCode * 59) + this.GeneratedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RowCount.GetHashCode();
                if (this.FileHash != null)
                {
                    hashCode = (hashCode * 59) + this.FileHash.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Encrypted.GetHashCode();
                if (this.Destinations != null)
                {
                    hashCode = (hashCode * 59) + this.Destinations.GetHashCode();
                }
                if (this.TransactionIds != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionIds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
