/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Response for bulk retry operation of failed deliveries
    /// </summary>
    [DataContract(Name = "TpfFailedDeliveryResponse")]
    public partial class TpfFailedDeliveryResponse : IEquatable<TpfFailedDeliveryResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfFailedDeliveryResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpfFailedDeliveryResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfFailedDeliveryResponse" /> class.
        /// </summary>
        /// <param name="submitted">Number of batch elements submitted for retry (required).</param>
        /// <param name="results">Per-element retry results (required).</param>
        public TpfFailedDeliveryResponse(int submitted = default(int), List<TpfRetryElementResult> results = default(List<TpfRetryElementResult>))
        {
            this.Submitted = submitted;
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for TpfFailedDeliveryResponse and cannot be null");
            }
            this.Results = results;
        }

        /// <summary>
        /// Number of batch elements submitted for retry
        /// </summary>
        /// <value>Number of batch elements submitted for retry</value>
        [DataMember(Name = "submitted", IsRequired = true, EmitDefaultValue = true)]
        public int Submitted { get; set; }

        /// <summary>
        /// Per-element retry results
        /// </summary>
        /// <value>Per-element retry results</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<TpfRetryElementResult> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpfFailedDeliveryResponse {\n");
            sb.Append("  Submitted: ").Append(Submitted).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpfFailedDeliveryResponse);
        }

        /// <summary>
        /// Returns true if TpfFailedDeliveryResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TpfFailedDeliveryResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpfFailedDeliveryResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Submitted == input.Submitted ||
                    this.Submitted.Equals(input.Submitted)
                ) && 
                (
                    this.Results == input.Results ||
                    this.Results != null &&
                    input.Results != null &&
                    this.Results.SequenceEqual(input.Results)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Submitted.GetHashCode();
                if (this.Results != null)
                {
                    hashCode = (hashCode * 59) + this.Results.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
