/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Information about a file delivery
    /// </summary>
    [DataContract(Name = "TpfFileDeliveryInfo")]
    public partial class TpfFileDeliveryInfo : IEquatable<TpfFileDeliveryInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfFileDeliveryInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpfFileDeliveryInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfFileDeliveryInfo" /> class.
        /// </summary>
        /// <param name="id">File delivery ID (required).</param>
        /// <param name="fileName">File name (required).</param>
        /// <param name="fileHash">SHA-256 hash of the file content (required).</param>
        /// <param name="destinationPath">SFTP destination path (required).</param>
        /// <param name="status">Delivery status (required).</param>
        /// <param name="generatedAt">Timestamp when the file was originally generated (required).</param>
        public TpfFileDeliveryInfo(long id = default(long), string fileName = default(string), string fileHash = default(string), string destinationPath = default(string), string status = default(string), DateTimeOffset generatedAt = default(DateTimeOffset))
        {
            this.Id = id;
            // to ensure "fileName" is required (not null)
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName is a required property for TpfFileDeliveryInfo and cannot be null");
            }
            this.FileName = fileName;
            // to ensure "fileHash" is required (not null)
            if (fileHash == null)
            {
                throw new ArgumentNullException("fileHash is a required property for TpfFileDeliveryInfo and cannot be null");
            }
            this.FileHash = fileHash;
            // to ensure "destinationPath" is required (not null)
            if (destinationPath == null)
            {
                throw new ArgumentNullException("destinationPath is a required property for TpfFileDeliveryInfo and cannot be null");
            }
            this.DestinationPath = destinationPath;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TpfFileDeliveryInfo and cannot be null");
            }
            this.Status = status;
            this.GeneratedAt = generatedAt;
        }

        /// <summary>
        /// File delivery ID
        /// </summary>
        /// <value>File delivery ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public long Id { get; set; }

        /// <summary>
        /// File name
        /// </summary>
        /// <value>File name</value>
        [DataMember(Name = "fileName", IsRequired = true, EmitDefaultValue = true)]
        public string FileName { get; set; }

        /// <summary>
        /// SHA-256 hash of the file content
        /// </summary>
        /// <value>SHA-256 hash of the file content</value>
        [DataMember(Name = "fileHash", IsRequired = true, EmitDefaultValue = true)]
        public string FileHash { get; set; }

        /// <summary>
        /// SFTP destination path
        /// </summary>
        /// <value>SFTP destination path</value>
        [DataMember(Name = "destinationPath", IsRequired = true, EmitDefaultValue = true)]
        public string DestinationPath { get; set; }

        /// <summary>
        /// Delivery status
        /// </summary>
        /// <value>Delivery status</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Timestamp when the file was originally generated
        /// </summary>
        /// <value>Timestamp when the file was originally generated</value>
        [DataMember(Name = "generatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset GeneratedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpfFileDeliveryInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  FileHash: ").Append(FileHash).Append("\n");
            sb.Append("  DestinationPath: ").Append(DestinationPath).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  GeneratedAt: ").Append(GeneratedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpfFileDeliveryInfo);
        }

        /// <summary>
        /// Returns true if TpfFileDeliveryInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of TpfFileDeliveryInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpfFileDeliveryInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.FileName == input.FileName ||
                    (this.FileName != null &&
                    this.FileName.Equals(input.FileName))
                ) && 
                (
                    this.FileHash == input.FileHash ||
                    (this.FileHash != null &&
                    this.FileHash.Equals(input.FileHash))
                ) && 
                (
                    this.DestinationPath == input.DestinationPath ||
                    (this.DestinationPath != null &&
                    this.DestinationPath.Equals(input.DestinationPath))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.GeneratedAt == input.GeneratedAt ||
                    (this.GeneratedAt != null &&
                    this.GeneratedAt.Equals(input.GeneratedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.FileName != null)
                {
                    hashCode = (hashCode * 59) + this.FileName.GetHashCode();
                }
                if (this.FileHash != null)
                {
                    hashCode = (hashCode * 59) + this.FileHash.GetHashCode();
                }
                if (this.DestinationPath != null)
                {
                    hashCode = (hashCode * 59) + this.DestinationPath.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.GeneratedAt != null)
                {
                    hashCode = (hashCode * 59) + this.GeneratedAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
