/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Request to retry failed deliveries for multiple batch elements. The integration instance identifier is supplied via the route, not the body.
    /// </summary>
    [DataContract(Name = "TpfRetryFailedDeliveryRequest")]
    public partial class TpfRetryFailedDeliveryRequest : IEquatable<TpfRetryFailedDeliveryRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetryFailedDeliveryRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpfRetryFailedDeliveryRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetryFailedDeliveryRequest" /> class.
        /// </summary>
        /// <param name="batchElementReferenceIds">Batch element reference identifiers to retry. No regex pattern is required as batch element IDs are vendor-defined strings with varying formats. (required).</param>
        public TpfRetryFailedDeliveryRequest(List<string> batchElementReferenceIds = default(List<string>))
        {
            // to ensure "batchElementReferenceIds" is required (not null)
            if (batchElementReferenceIds == null)
            {
                throw new ArgumentNullException("batchElementReferenceIds is a required property for TpfRetryFailedDeliveryRequest and cannot be null");
            }
            this.BatchElementReferenceIds = batchElementReferenceIds;
        }

        /// <summary>
        /// Batch element reference identifiers to retry. No regex pattern is required as batch element IDs are vendor-defined strings with varying formats.
        /// </summary>
        /// <value>Batch element reference identifiers to retry. No regex pattern is required as batch element IDs are vendor-defined strings with varying formats.</value>
        [DataMember(Name = "batchElementReferenceIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> BatchElementReferenceIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpfRetryFailedDeliveryRequest {\n");
            sb.Append("  BatchElementReferenceIds: ").Append(BatchElementReferenceIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpfRetryFailedDeliveryRequest);
        }

        /// <summary>
        /// Returns true if TpfRetryFailedDeliveryRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TpfRetryFailedDeliveryRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpfRetryFailedDeliveryRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BatchElementReferenceIds == input.BatchElementReferenceIds ||
                    this.BatchElementReferenceIds != null &&
                    input.BatchElementReferenceIds != null &&
                    this.BatchElementReferenceIds.SequenceEqual(input.BatchElementReferenceIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BatchElementReferenceIds != null)
                {
                    hashCode = (hashCode * 59) + this.BatchElementReferenceIds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
