/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Response from retrying SFTP file delivery
    /// </summary>
    [DataContract(Name = "TpfRetrySftpResponse")]
    public partial class TpfRetrySftpResponse : IEquatable<TpfRetrySftpResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetrySftpResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpfRetrySftpResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetrySftpResponse" /> class.
        /// </summary>
        /// <param name="success">Whether the retry was successful (required).</param>
        /// <param name="message">Status message describing the result (required).</param>
        /// <param name="newFileDeliveryId">ID of the new file delivery record created for this retry (if successful).</param>
        /// <param name="retriedAt">Timestamp when the retry was executed.</param>
        /// <param name="originalFile">originalFile.</param>
        /// <param name="duplicateFile">duplicateFile.</param>
        public TpfRetrySftpResponse(bool success = default(bool), string message = default(string), long? newFileDeliveryId = default(long?), DateTimeOffset? retriedAt = default(DateTimeOffset?), TpfFileDeliveryInfo originalFile = default(TpfFileDeliveryInfo), TpfFileDeliveryInfo duplicateFile = default(TpfFileDeliveryInfo))
        {
            this.Success = success;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for TpfRetrySftpResponse and cannot be null");
            }
            this.Message = message;
            this.NewFileDeliveryId = newFileDeliveryId;
            this.RetriedAt = retriedAt;
            this.OriginalFile = originalFile;
            this.DuplicateFile = duplicateFile;
        }

        /// <summary>
        /// Whether the retry was successful
        /// </summary>
        /// <value>Whether the retry was successful</value>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Status message describing the result
        /// </summary>
        /// <value>Status message describing the result</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// ID of the new file delivery record created for this retry (if successful)
        /// </summary>
        /// <value>ID of the new file delivery record created for this retry (if successful)</value>
        [DataMember(Name = "newFileDeliveryId", EmitDefaultValue = true)]
        public long? NewFileDeliveryId { get; set; }

        /// <summary>
        /// Timestamp when the retry was executed
        /// </summary>
        /// <value>Timestamp when the retry was executed</value>
        [DataMember(Name = "retriedAt", EmitDefaultValue = true)]
        public DateTimeOffset? RetriedAt { get; set; }

        /// <summary>
        /// Gets or Sets OriginalFile
        /// </summary>
        [DataMember(Name = "originalFile", EmitDefaultValue = false)]
        public TpfFileDeliveryInfo OriginalFile { get; set; }

        /// <summary>
        /// Gets or Sets DuplicateFile
        /// </summary>
        [DataMember(Name = "duplicateFile", EmitDefaultValue = false)]
        public TpfFileDeliveryInfo DuplicateFile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpfRetrySftpResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  NewFileDeliveryId: ").Append(NewFileDeliveryId).Append("\n");
            sb.Append("  RetriedAt: ").Append(RetriedAt).Append("\n");
            sb.Append("  OriginalFile: ").Append(OriginalFile).Append("\n");
            sb.Append("  DuplicateFile: ").Append(DuplicateFile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpfRetrySftpResponse);
        }

        /// <summary>
        /// Returns true if TpfRetrySftpResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TpfRetrySftpResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpfRetrySftpResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.NewFileDeliveryId == input.NewFileDeliveryId ||
                    (this.NewFileDeliveryId != null &&
                    this.NewFileDeliveryId.Equals(input.NewFileDeliveryId))
                ) && 
                (
                    this.RetriedAt == input.RetriedAt ||
                    (this.RetriedAt != null &&
                    this.RetriedAt.Equals(input.RetriedAt))
                ) && 
                (
                    this.OriginalFile == input.OriginalFile ||
                    (this.OriginalFile != null &&
                    this.OriginalFile.Equals(input.OriginalFile))
                ) && 
                (
                    this.DuplicateFile == input.DuplicateFile ||
                    (this.DuplicateFile != null &&
                    this.DuplicateFile.Equals(input.DuplicateFile))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Success.GetHashCode();
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                if (this.NewFileDeliveryId != null)
                {
                    hashCode = (hashCode * 59) + this.NewFileDeliveryId.GetHashCode();
                }
                if (this.RetriedAt != null)
                {
                    hashCode = (hashCode * 59) + this.RetriedAt.GetHashCode();
                }
                if (this.OriginalFile != null)
                {
                    hashCode = (hashCode * 59) + this.OriginalFile.GetHashCode();
                }
                if (this.DuplicateFile != null)
                {
                    hashCode = (hashCode * 59) + this.DuplicateFile.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
