/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Result for a single batch element retry attempt
    /// </summary>
    [DataContract(Name = "TpfRetryElementResult")]
    public partial class TpfRetryElementResult : IEquatable<TpfRetryElementResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetryElementResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpfRetryElementResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpfRetryElementResult" /> class.
        /// </summary>
        /// <param name="batchElementReferenceId">Batch element reference identifier (required).</param>
        /// <param name="status">Status of the retry attempt (e.g., \&quot;Retrying\&quot;, \&quot;NotFound\&quot;) (required).</param>
        public TpfRetryElementResult(string batchElementReferenceId = default(string), string status = default(string))
        {
            // to ensure "batchElementReferenceId" is required (not null)
            if (batchElementReferenceId == null)
            {
                throw new ArgumentNullException("batchElementReferenceId is a required property for TpfRetryElementResult and cannot be null");
            }
            this.BatchElementReferenceId = batchElementReferenceId;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TpfRetryElementResult and cannot be null");
            }
            this.Status = status;
        }

        /// <summary>
        /// Batch element reference identifier
        /// </summary>
        /// <value>Batch element reference identifier</value>
        [DataMember(Name = "batchElementReferenceId", IsRequired = true, EmitDefaultValue = true)]
        public string BatchElementReferenceId { get; set; }

        /// <summary>
        /// Status of the retry attempt (e.g., \&quot;Retrying\&quot;, \&quot;NotFound\&quot;)
        /// </summary>
        /// <value>Status of the retry attempt (e.g., \&quot;Retrying\&quot;, \&quot;NotFound\&quot;)</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TpfRetryElementResult {\n");
            sb.Append("  BatchElementReferenceId: ").Append(BatchElementReferenceId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpfRetryElementResult);
        }

        /// <summary>
        /// Returns true if TpfRetryElementResult instances are equal
        /// </summary>
        /// <param name="input">Instance of TpfRetryElementResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpfRetryElementResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BatchElementReferenceId == input.BatchElementReferenceId ||
                    (this.BatchElementReferenceId != null &&
                    this.BatchElementReferenceId.Equals(input.BatchElementReferenceId))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BatchElementReferenceId != null)
                {
                    hashCode = (hashCode * 59) + this.BatchElementReferenceId.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
