/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// Response containing details of a single transaction for a run.
    /// </summary>
    [DataContract(Name = "TransactionResponse")]
    public partial class TransactionResponse : IEquatable<TransactionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionResponse" /> class.
        /// </summary>
        /// <param name="transactionId">transactionId (required).</param>
        /// <param name="publicationStatus">publicationStatus (required).</param>
        /// <param name="portfolioScope">portfolioScope.</param>
        /// <param name="portfolioCode">portfolioCode.</param>
        /// <param name="instrumentId">instrumentId (required).</param>
        /// <param name="instrumentType">instrumentType (required).</param>
        /// <param name="instrumentName">instrumentName (required).</param>
        /// <param name="tradeDate">tradeDate (required).</param>
        /// <param name="settlementDate">settlementDate (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="skipReason">skipReason.</param>
        /// <param name="failureReason">failureReason.</param>
        /// <param name="outputFileName">outputFileName.</param>
        /// <param name="sentAt">sentAt.</param>
        /// <param name="destinations">destinations (required).</param>
        public TransactionResponse(string transactionId = default(string), string publicationStatus = default(string), string portfolioScope = default(string), string portfolioCode = default(string), string instrumentId = default(string), string instrumentType = default(string), string instrumentName = default(string), DateTimeOffset tradeDate = default(DateTimeOffset), DateTimeOffset settlementDate = default(DateTimeOffset), string status = default(string), string skipReason = default(string), string failureReason = default(string), string outputFileName = default(string), DateTimeOffset? sentAt = default(DateTimeOffset?), List<DestinationResponse> destinations = default(List<DestinationResponse>))
        {
            // to ensure "transactionId" is required (not null)
            if (transactionId == null)
            {
                throw new ArgumentNullException("transactionId is a required property for TransactionResponse and cannot be null");
            }
            this.TransactionId = transactionId;
            // to ensure "publicationStatus" is required (not null)
            if (publicationStatus == null)
            {
                throw new ArgumentNullException("publicationStatus is a required property for TransactionResponse and cannot be null");
            }
            this.PublicationStatus = publicationStatus;
            // to ensure "instrumentId" is required (not null)
            if (instrumentId == null)
            {
                throw new ArgumentNullException("instrumentId is a required property for TransactionResponse and cannot be null");
            }
            this.InstrumentId = instrumentId;
            // to ensure "instrumentType" is required (not null)
            if (instrumentType == null)
            {
                throw new ArgumentNullException("instrumentType is a required property for TransactionResponse and cannot be null");
            }
            this.InstrumentType = instrumentType;
            // to ensure "instrumentName" is required (not null)
            if (instrumentName == null)
            {
                throw new ArgumentNullException("instrumentName is a required property for TransactionResponse and cannot be null");
            }
            this.InstrumentName = instrumentName;
            this.TradeDate = tradeDate;
            this.SettlementDate = settlementDate;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TransactionResponse and cannot be null");
            }
            this.Status = status;
            // to ensure "destinations" is required (not null)
            if (destinations == null)
            {
                throw new ArgumentNullException("destinations is a required property for TransactionResponse and cannot be null");
            }
            this.Destinations = destinations;
            this.PortfolioScope = portfolioScope;
            this.PortfolioCode = portfolioCode;
            this.SkipReason = skipReason;
            this.FailureReason = failureReason;
            this.OutputFileName = outputFileName;
            this.SentAt = sentAt;
        }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets PublicationStatus
        /// </summary>
        [DataMember(Name = "publicationStatus", IsRequired = true, EmitDefaultValue = true)]
        public string PublicationStatus { get; set; }

        /// <summary>
        /// Gets or Sets PortfolioScope
        /// </summary>
        [DataMember(Name = "portfolioScope", EmitDefaultValue = true)]
        public string PortfolioScope { get; set; }

        /// <summary>
        /// Gets or Sets PortfolioCode
        /// </summary>
        [DataMember(Name = "portfolioCode", EmitDefaultValue = true)]
        public string PortfolioCode { get; set; }

        /// <summary>
        /// Gets or Sets InstrumentId
        /// </summary>
        [DataMember(Name = "instrumentId", IsRequired = true, EmitDefaultValue = true)]
        public string InstrumentId { get; set; }

        /// <summary>
        /// Gets or Sets InstrumentType
        /// </summary>
        [DataMember(Name = "instrumentType", IsRequired = true, EmitDefaultValue = true)]
        public string InstrumentType { get; set; }

        /// <summary>
        /// Gets or Sets InstrumentName
        /// </summary>
        [DataMember(Name = "instrumentName", IsRequired = true, EmitDefaultValue = true)]
        public string InstrumentName { get; set; }

        /// <summary>
        /// Gets or Sets TradeDate
        /// </summary>
        [DataMember(Name = "tradeDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset TradeDate { get; set; }

        /// <summary>
        /// Gets or Sets SettlementDate
        /// </summary>
        [DataMember(Name = "settlementDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset SettlementDate { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets SkipReason
        /// </summary>
        [DataMember(Name = "skipReason", EmitDefaultValue = true)]
        public string SkipReason { get; set; }

        /// <summary>
        /// Gets or Sets FailureReason
        /// </summary>
        [DataMember(Name = "failureReason", EmitDefaultValue = true)]
        public string FailureReason { get; set; }

        /// <summary>
        /// Gets or Sets OutputFileName
        /// </summary>
        [DataMember(Name = "outputFileName", EmitDefaultValue = true)]
        public string OutputFileName { get; set; }

        /// <summary>
        /// Gets or Sets SentAt
        /// </summary>
        [DataMember(Name = "sentAt", EmitDefaultValue = true)]
        public DateTimeOffset? SentAt { get; set; }

        /// <summary>
        /// Gets or Sets Destinations
        /// </summary>
        [DataMember(Name = "destinations", IsRequired = true, EmitDefaultValue = true)]
        public List<DestinationResponse> Destinations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionResponse {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  PublicationStatus: ").Append(PublicationStatus).Append("\n");
            sb.Append("  PortfolioScope: ").Append(PortfolioScope).Append("\n");
            sb.Append("  PortfolioCode: ").Append(PortfolioCode).Append("\n");
            sb.Append("  InstrumentId: ").Append(InstrumentId).Append("\n");
            sb.Append("  InstrumentType: ").Append(InstrumentType).Append("\n");
            sb.Append("  InstrumentName: ").Append(InstrumentName).Append("\n");
            sb.Append("  TradeDate: ").Append(TradeDate).Append("\n");
            sb.Append("  SettlementDate: ").Append(SettlementDate).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  SkipReason: ").Append(SkipReason).Append("\n");
            sb.Append("  FailureReason: ").Append(FailureReason).Append("\n");
            sb.Append("  OutputFileName: ").Append(OutputFileName).Append("\n");
            sb.Append("  SentAt: ").Append(SentAt).Append("\n");
            sb.Append("  Destinations: ").Append(Destinations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionResponse);
        }

        /// <summary>
        /// Returns true if TransactionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransactionId == input.TransactionId ||
                    (this.TransactionId != null &&
                    this.TransactionId.Equals(input.TransactionId))
                ) && 
                (
                    this.PublicationStatus == input.PublicationStatus ||
                    (this.PublicationStatus != null &&
                    this.PublicationStatus.Equals(input.PublicationStatus))
                ) && 
                (
                    this.PortfolioScope == input.PortfolioScope ||
                    (this.PortfolioScope != null &&
                    this.PortfolioScope.Equals(input.PortfolioScope))
                ) && 
                (
                    this.PortfolioCode == input.PortfolioCode ||
                    (this.PortfolioCode != null &&
                    this.PortfolioCode.Equals(input.PortfolioCode))
                ) && 
                (
                    this.InstrumentId == input.InstrumentId ||
                    (this.InstrumentId != null &&
                    this.InstrumentId.Equals(input.InstrumentId))
                ) && 
                (
                    this.InstrumentType == input.InstrumentType ||
                    (this.InstrumentType != null &&
                    this.InstrumentType.Equals(input.InstrumentType))
                ) && 
                (
                    this.InstrumentName == input.InstrumentName ||
                    (this.InstrumentName != null &&
                    this.InstrumentName.Equals(input.InstrumentName))
                ) && 
                (
                    this.TradeDate == input.TradeDate ||
                    (this.TradeDate != null &&
                    this.TradeDate.Equals(input.TradeDate))
                ) && 
                (
                    this.SettlementDate == input.SettlementDate ||
                    (this.SettlementDate != null &&
                    this.SettlementDate.Equals(input.SettlementDate))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.SkipReason == input.SkipReason ||
                    (this.SkipReason != null &&
                    this.SkipReason.Equals(input.SkipReason))
                ) && 
                (
                    this.FailureReason == input.FailureReason ||
                    (this.FailureReason != null &&
                    this.FailureReason.Equals(input.FailureReason))
                ) && 
                (
                    this.OutputFileName == input.OutputFileName ||
                    (this.OutputFileName != null &&
                    this.OutputFileName.Equals(input.OutputFileName))
                ) && 
                (
                    this.SentAt == input.SentAt ||
                    (this.SentAt != null &&
                    this.SentAt.Equals(input.SentAt))
                ) && 
                (
                    this.Destinations == input.Destinations ||
                    this.Destinations != null &&
                    input.Destinations != null &&
                    this.Destinations.SequenceEqual(input.Destinations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionId != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionId.GetHashCode();
                }
                if (this.PublicationStatus != null)
                {
                    hashCode = (hashCode * 59) + this.PublicationStatus.GetHashCode();
                }
                if (this.PortfolioScope != null)
                {
                    hashCode = (hashCode * 59) + this.PortfolioScope.GetHashCode();
                }
                if (this.PortfolioCode != null)
                {
                    hashCode = (hashCode * 59) + this.PortfolioCode.GetHashCode();
                }
                if (this.InstrumentId != null)
                {
                    hashCode = (hashCode * 59) + this.InstrumentId.GetHashCode();
                }
                if (this.InstrumentType != null)
                {
                    hashCode = (hashCode * 59) + this.InstrumentType.GetHashCode();
                }
                if (this.InstrumentName != null)
                {
                    hashCode = (hashCode * 59) + this.InstrumentName.GetHashCode();
                }
                if (this.TradeDate != null)
                {
                    hashCode = (hashCode * 59) + this.TradeDate.GetHashCode();
                }
                if (this.SettlementDate != null)
                {
                    hashCode = (hashCode * 59) + this.SettlementDate.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.SkipReason != null)
                {
                    hashCode = (hashCode * 59) + this.SkipReason.GetHashCode();
                }
                if (this.FailureReason != null)
                {
                    hashCode = (hashCode * 59) + this.FailureReason.GetHashCode();
                }
                if (this.OutputFileName != null)
                {
                    hashCode = (hashCode * 59) + this.OutputFileName.GetHashCode();
                }
                if (this.SentAt != null)
                {
                    hashCode = (hashCode * 59) + this.SentAt.GetHashCode();
                }
                if (this.Destinations != null)
                {
                    hashCode = (hashCode * 59) + this.Destinations.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
