/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Horizon.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Horizon.Sdk.Model
{
    /// <summary>
    /// The result fields an instance returns to the Workflow task that started its run.
    /// </summary>
    [DataContract(Name = "WorkflowResultFieldsResponse")]
    public partial class WorkflowResultFieldsResponse : IEquatable<WorkflowResultFieldsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResultFieldsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowResultFieldsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResultFieldsResponse" /> class.
        /// </summary>
        /// <param name="instanceId">The instance these fields belong to. (required).</param>
        /// <param name="reportsToWorkflow">Whether this instance has an enabled RunWorkflow post-process task at all. (required).</param>
        /// <param name="resultFields">Every distinct field declared across this instance&#39;s RunWorkflow tasks. (required).</param>
        /// <param name="tasks">Per-task breakdown: an instance may declare different fields on success and on failure. (required).</param>
        public WorkflowResultFieldsResponse(string instanceId = default(string), bool reportsToWorkflow = default(bool), List<WorkflowResultFieldResponse> resultFields = default(List<WorkflowResultFieldResponse>), List<WorkflowResultFieldsTaskResponse> tasks = default(List<WorkflowResultFieldsTaskResponse>))
        {
            // to ensure "instanceId" is required (not null)
            if (instanceId == null)
            {
                throw new ArgumentNullException("instanceId is a required property for WorkflowResultFieldsResponse and cannot be null");
            }
            this.InstanceId = instanceId;
            this.ReportsToWorkflow = reportsToWorkflow;
            // to ensure "resultFields" is required (not null)
            if (resultFields == null)
            {
                throw new ArgumentNullException("resultFields is a required property for WorkflowResultFieldsResponse and cannot be null");
            }
            this.ResultFields = resultFields;
            // to ensure "tasks" is required (not null)
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks is a required property for WorkflowResultFieldsResponse and cannot be null");
            }
            this.Tasks = tasks;
        }

        /// <summary>
        /// The instance these fields belong to.
        /// </summary>
        /// <value>The instance these fields belong to.</value>
        [DataMember(Name = "instanceId", IsRequired = true, EmitDefaultValue = true)]
        public string InstanceId { get; set; }

        /// <summary>
        /// Whether this instance has an enabled RunWorkflow post-process task at all.
        /// </summary>
        /// <value>Whether this instance has an enabled RunWorkflow post-process task at all.</value>
        [DataMember(Name = "reportsToWorkflow", IsRequired = true, EmitDefaultValue = true)]
        public bool ReportsToWorkflow { get; set; }

        /// <summary>
        /// Every distinct field declared across this instance&#39;s RunWorkflow tasks.
        /// </summary>
        /// <value>Every distinct field declared across this instance&#39;s RunWorkflow tasks.</value>
        [DataMember(Name = "resultFields", IsRequired = true, EmitDefaultValue = true)]
        public List<WorkflowResultFieldResponse> ResultFields { get; set; }

        /// <summary>
        /// Per-task breakdown: an instance may declare different fields on success and on failure.
        /// </summary>
        /// <value>Per-task breakdown: an instance may declare different fields on success and on failure.</value>
        [DataMember(Name = "tasks", IsRequired = true, EmitDefaultValue = true)]
        public List<WorkflowResultFieldsTaskResponse> Tasks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowResultFieldsResponse {\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  ReportsToWorkflow: ").Append(ReportsToWorkflow).Append("\n");
            sb.Append("  ResultFields: ").Append(ResultFields).Append("\n");
            sb.Append("  Tasks: ").Append(Tasks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkflowResultFieldsResponse);
        }

        /// <summary>
        /// Returns true if WorkflowResultFieldsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkflowResultFieldsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkflowResultFieldsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.InstanceId == input.InstanceId ||
                    (this.InstanceId != null &&
                    this.InstanceId.Equals(input.InstanceId))
                ) && 
                (
                    this.ReportsToWorkflow == input.ReportsToWorkflow ||
                    this.ReportsToWorkflow.Equals(input.ReportsToWorkflow)
                ) && 
                (
                    this.ResultFields == input.ResultFields ||
                    this.ResultFields != null &&
                    input.ResultFields != null &&
                    this.ResultFields.SequenceEqual(input.ResultFields)
                ) && 
                (
                    this.Tasks == input.Tasks ||
                    this.Tasks != null &&
                    input.Tasks != null &&
                    this.Tasks.SequenceEqual(input.Tasks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InstanceId != null)
                {
                    hashCode = (hashCode * 59) + this.InstanceId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReportsToWorkflow.GetHashCode();
                if (this.ResultFields != null)
                {
                    hashCode = (hashCode * 59) + this.ResultFields.GetHashCode();
                }
                if (this.Tasks != null)
                {
                    hashCode = (hashCode * 59) + this.Tasks.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
